version: '3.8'

services:
  pipecat-bot:
    build: .
    ports:
      - "7860:7860"
    env_file:
      - .env
    volumes:
      - ./templates:/app/templates
    restart: unless-stopped
    command: ["python", "bot.py", "--transport", "twilio", "--proxy", "dfd3fc713caa.ngrok-free.app", "--host", "0.0.0.0"]